/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin source files
*/
var c=Object.defineProperty;var d=Object.getOwnPropertyDescriptor;var h=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var p=(r,t)=>{for(var n in t)c(r,n,{get:t[n],enumerable:!0})},u=(r,t,n,a)=>{if(t&&typeof t=="object"||typeof t=="function")for(let e of h(t))!g.call(r,e)&&e!==n&&c(r,e,{get:()=>t[e],enumerable:!(a=d(t,e))||a.enumerable});return r};var m=r=>u(c({},"__esModule",{value:!0}),r);var v={};p(v,{default:()=>i});module.exports=m(v);var s=require("obsidian"),l="\u65E5\u8BB0",$=["calm","focused","curious","steady","bright","reflective"],y=["sunny","cloudy","light rain","breezy","warm","quiet night"],f=["\u4ECA\u5929\u6700\u503C\u5F97\u8BB0\u4F4F\u7684\u4E00\u4EF6\u5C0F\u4E8B\u662F\u4EC0\u4E48\uFF1F","\u6709\u6CA1\u6709\u4E00\u4E2A\u77AC\u95F4\u8BA9\u4F60\u611F\u89C9\u81EA\u5DF1\u6B63\u5728\u5F80\u524D\u8D70\uFF1F","\u5982\u679C\u7ED9\u4ECA\u5929\u53D6\u4E00\u4E2A\u6807\u9898\uFF0C\u4F60\u4F1A\u600E\u4E48\u547D\u540D\uFF1F","\u4ECA\u5929\u6709\u4EC0\u4E48\u53EF\u4EE5\u7559\u7ED9\u660E\u5929\u7EE7\u7EED\u505A\uFF1F","\u54EA\u4EF6\u4E8B\u8BA9\u4F60\u6BD4\u65E9\u4E0A\u66F4\u8F7B\u677E\u4E86\u4E00\u70B9\uFF1F"],i=class extends s.Plugin{async onload(){this.addCommand({id:"create-random-diary",name:"\u5199\u5165\u968F\u673A\u65E5\u8BB0",callback:async()=>{let t=await this.createRandomDiary();new s.Notice(`\u5DF2\u521B\u5EFA\u65E5\u8BB0\uFF1A${t.path}`)}})}async createRandomDiary(){await this.ensureFolder(l);let t=new Date,n=this.formatDate(t),a=await this.getAvailablePath(`${l}/${n}.md`),e=this.buildDiaryContent(n);return this.app.vault.create(a,e)}buildDiaryContent(t){let n=this.pick($),a=this.pick(y),e=this.pick(f);return`---
date: ${t}
mood: ${n}
weather: ${a}
tags:
  - diary
  - generated
---

# ${t}

${e}

\u4ECA\u5929\u53EF\u4EE5\u5148\u5199\u4E09\u53E5\u8BDD\uFF1A

1. 
2. 
3. 

## \u4ECA\u65E5\u788E\u7247

- \u5FC3\u60C5\uFF1A${n}
- \u5929\u6C14\uFF1A${a}
- \u5173\u952E\u8BCD\uFF1A
`}async ensureFolder(t){this.app.vault.getAbstractFileByPath(t)||await this.app.vault.createFolder(t)}async getAvailablePath(t){if(!this.app.vault.getAbstractFileByPath(t))return t;let n=t.lastIndexOf("."),a=n>=0?t.slice(0,n):t,e=n>=0?t.slice(n):"",o=2;for(;this.app.vault.getAbstractFileByPath(`${a}-${o}${e}`);)o+=1;return`${a}-${o}${e}`}formatDate(t){let n=t.getFullYear(),a=String(t.getMonth()+1).padStart(2,"0"),e=String(t.getDate()).padStart(2,"0");return`${n}-${a}-${e}`}pick(t){return t[Math.floor(Math.random()*t.length)]}};
